BikeRental/Controllers/BikeBookingController.cs
using BikeRental.Model.Entities;
using BikeRental.ViewModel;
using BikeRental.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace BikeRental.Controllers
{
    [Authorize]
    public class BikeBookingController : Controller
    {
        private readonly IBookingRepository _bookingRepo;
        private readonly UserManager<IdentityUser> _user;

        public BikeBookingController(IBookingRepository bookingRepo, UserManager<IdentityUser> user)
        {
            _bookingRepo = bookingRepo;
            _user = user;
        }

        public async Task<IActionResult> Index()
        {
            var bookings = await _bookingRepo.GetBookings();

            if (bookings == null)
                return NoContent();

            return View(bookings);
        }
        
        public async Task<IActionResult> Detail(Guid? id)
        {
            var booking = await _bookingRepo.GetBooking(id);

            if (booking == null)
                return NotFound();

            return View(booking);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            var booking = await _bookingRepo.GetBooking(id);

            if (booking == null)
                return NotFound();

            return View(booking);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind(include: new string[] { "RentalId", "SelectedCustomerId", "SelectedBikeId", "Status", "RentedDate", "ReturnedDate" })] BikeBookingViewModel model)
        {
            if (ModelState.IsValid)
            {
                var currentUser = await _user.GetUserAsync(User);

                model.ModifiedDate = DateTime.Now;
                model.ModifiedBy = currentUser.Email;

                var response = await _bookingRepo.UpdateBooking(model);

                if (response)
                    return RedirectToAction("Index");
            }

            return NoContent();
        }

        public IActionResult Create()
        {
            var booking = _bookingRepo.CreateBooking();

            return View(booking);
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind(include: new string[] { "RentalId", "SelectedCustomerId", "SelectedBikeId", "Status", "RentedDate", "ReturnedDate" })] BikeBookingViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await _bookingRepo.SaveBooking(model);

                if (response)
                    return RedirectToAction("Index");
            }

            return NoContent();
        }
    }
}

BikeRental/Controllers/BikeController.cs
using BikeRental.ViewModel;
using BikeRental.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace BikeRentalService.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BikeController : Controller
    {
        private readonly IBikeRepository _bikeRepo;
        public BikeController(IBikeRepository bikeRepo)
        {
            _bikeRepo = bikeRepo;
        }

        public async Task<IActionResult> Index()
        {
            var bikes = await _bikeRepo.GetBikes();

            if (bikes == null)
                return NoContent();

            return View(bikes);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            var bike = await _bikeRepo.GetBike(id);

            if (bike == null)
                return NotFound();

            return View(bike);
        }

        public async Task<IActionResult> Detail(Guid? id)
        {
            var bike = await _bikeRepo.GetBike(id);

            if (bike == null)
                return NotFound();

            return View(bike);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind(include: new string[] { "BikeId", "ModelNo", "Brand", "Status", "SelectedBikeType", "SelectBikeTypeId" })] BikeViewModel model)
        {
            if(ModelState.IsValid)
            {
                var response = await _bikeRepo.UpdateBike(model);

                if (response)
                    return RedirectToAction("Index");
            }

            return NoContent();
        }

        public IActionResult Create()
        {
            var bike = _bikeRepo.CreateBike();

            return View(bike);
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind(include: new string[] { "BikeId", "ModelNo", "Brand", "Status", "SelectedBikeType", "SelectBikeTypeId" })] BikeViewModel model)
        {
            if(ModelState.IsValid)
            {
                var response = await _bikeRepo.SaveBike(model);

                if (response)
                    return RedirectToAction("Index");
            }

            return NoContent();
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            var bike = await _bikeRepo.GetBike(id);

            if (bike == null)
                return NotFound();

            return View(bike);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(Guid? BikeId)
        {
            if (ModelState.IsValid)
            {
                var response = await _bikeRepo.DeleteBike(BikeId);

                if (response)
                    return RedirectToAction("Index");
            }

            return NoContent();
        }
    }
}

BikeRental/Controllers/CustomerController.cs
using BikeRental.Model.Entities;
using BikeRental.ViewModel;
using BikeRental.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace BikeRental.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CustomerController : Controller
    {
        private readonly ICustomerRepository _customerRepo;

        public CustomerController(ICustomerRepository customerRepo)
        {
            _customerRepo = customerRepo;
        }

        public async Task<IActionResult> Index()
        {
            var customers = await _customerRepo.GetCustomers();

            if (customers == null)
                return NoContent();

            return View(customers);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            var customer = await _customerRepo.GetCustomer(id);

            if (customer == null)
                return NotFound();

            return View(customer);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind(include: new string[] { "CustomerId", "FirstName", "LastName", "Address", "BirthDate", "Status" })] CustomerViewModel model)
        {
            if(ModelState.IsValid)
            {
                var response = await _customerRepo.UpdateCustomer(model);

                if (response)
                    return RedirectToAction("Index");
            }

            return NoContent();
        }

        public IActionResult Create()
        {
            var customer = _customerRepo.CreateCustomer();

            return View(customer);
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind(include: new string[] { "CustomerId", "FirstName", "LastName", "Address", "BirthDate", "Status" })] CustomerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await _customerRepo.SaveCustomer(model);

                if (response)
                    return RedirectToAction("Index");
            }

            return NoContent();
        }

        public async Task<IActionResult> Detail(Guid? id)
        {
            var customer = await _customerRepo.GetCustomer(id);

            if (customer == null)
                return NotFound();

            return View(customer);
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            var customer = await _customerRepo.GetCustomer(id);

            if (customer == null)
                return NotFound();

            return View(customer);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(Guid? CustomerId)
        {
            if (ModelState.IsValid)
            {
                var response = await _customerRepo.DeleteCustomer(CustomerId);

                if (response)
                    return RedirectToAction("Index");
            }

            return NoContent();
        }
    }
}

BikeRental/Controllers/UserController.cs
using BikeRental.Model.Entities;
using BikeRental.ViewModel;
using BikeRental.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace BikeRental.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly ICustomerRepository _customerRepo;

        public UserController(ICustomerRepository customerRepo)
        {
            _customerRepo = customerRepo;
        }

        public async Task<IActionResult> Index()
        {
            var customers = await _customerRepo.GetCustomers();

            if (customers == null)
                return NoContent();

            return View(customers);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            var customer = await _customerRepo.GetCustomer(id);

            if (customer == null)
                return NotFound();

            return View(customer);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([Bind(include: new string[] { "CustomerId", "FirstName", "LastName", "Address", "BirthDate", "Status" })] CustomerViewModel model)
        {
            if(ModelState.IsValid)
            {
                var response = await _customerRepo.UpdateCustomer(model);

                if (response)
                    return RedirectToAction("Index");
            }

            return NoContent();
        }

        public IActionResult Create()
        {
            var customer = _customerRepo.CreateCustomer();

            return View(customer);
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind(include: new string[] { "CustomerId", "FirstName", "LastName", "Address", "BirthDate", "Status" })] CustomerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await _customerRepo.SaveCustomer(model);

                if (response)
                    return RedirectToAction("Index");
            }

            return NoContent();
        }

        public async Task<IActionResult> Detail(Guid? id)
        {
            var customer = await _customerRepo.GetCustomer(id);

            if (customer == null)
                return NotFound();

            return View(customer);
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            var customer = await _customerRepo.GetCustomer(id);

            if (customer == null)
                return NotFound();

            return View(customer);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(Guid? CustomerId)
        {
            if (ModelState.IsValid)
            {
                var response = await _customerRepo.DeleteCustomer(CustomerId);

                if (response)
                    return RedirectToAction("Index");
            }

            return NoContent();
        }
    }
}

BikeRental/Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BikeRental</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                
                <a class="navbar-brand" asp-area="" asp-page="/Index">BikeRental</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if(SignInManager.IsSignedIn(User))
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="BikeBooking" asp-action="Index">Bike Booking</a>
                                </li>
                                @if (User.IsInRole("Admin"))
                            {
                                 <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-action="Index">Administration</a>
                                    <ul>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Bike" asp-action="Index">Bikes</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                                        </li>
                                    </ul>
                                </li>
                            }
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                                </li>
                            </ul>
                            <ul class="navbar-nav d-flex-column justify-content-end">
                                <li class="nav-item">
                                    <div class="text-dark justify-content-start">Hello, @UserManager.GetUserName(User)!&nbsp;&nbsp;&nbsp;</div>
                                </li>
                                <li class="nav-item">
                                    <a class="btn btn-primary" asp-area="" asp-page="/Logout">Logout</a>
                                </li>
                            </ul>
                        }
                        else
                        {
                            <ul class="navbar-nav d-flex-column justify-content-end flex-grow-1">
                                <li>
                                    <a asp-page="/Login" class="btn btn-primary">Login</a>
                                </li>
                                <li>
                                    <a asp-page="/Register" class="btn">Register</a>
                                </li>
                            </ul>
                        }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BikeRental - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>