BikeRental/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BikeRental.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

BikeRental/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BikeRental.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

BikeRental/Pages/Login.cshtml.cs
using BikeRental.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace BikeRental.Pages
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<IdentityUser> signInManager;

        [BindProperty]
        public LoginViewModel Model { get; set; }
        public LoginModel(SignInManager<IdentityUser> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        { 
            if(ModelState.IsValid)
            {
               var identityResult = await signInManager.PasswordSignInAsync(Model.Email, Model.Password, Model.RememberMe, false);
                if (identityResult.Succeeded)
                {
                    if(returnUrl == null || returnUrl == "/")
                    {
                        return RedirectToPage("Index");
                    }
                    else
                    {
                        return RedirectToPage(returnUrl);
                    }
                }

                ModelState.AddModelError("", "Username or Password is incorrect");
            }

            return Page();
        }
    }
}

BikeRental/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace BikeRental.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> signInManager;

        public LogoutModel(SignInManager<IdentityUser> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("Login");
        }
        public IActionResult OnPostDontLogoutAsync()
        {
            return RedirectToPage("Index");
        }
    }
}

BikeRental/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BikeRental.Pages
{
    [Authorize]
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

BikeRental/Pages/Register.cshtml.cs
using BikeRental.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace BikeRental.Pages
{
    public class RegisterModel : PageModel
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        [BindProperty]
        public RegisterViewModel Model { get; set; }
        public RegisterModel(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }
        
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if(ModelState.IsValid)
            {
                var user = new IdentityUser()
                {
                    UserName = Model.Email,
                    Email = Model.Email
                };

                var result = await userManager.CreateAsync(user, Model.Password);
                if (result.Succeeded)
                {
                    return RedirectToPage("SuccessRegistration");
                }

                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return Page();
        }
    }
}

BikeRental/Pages/SuccessRegistration.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BikeRental.Pages
{
    public class SuccessRegistrationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BikeRental/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BikeRental/Pages/Login.cshtml
@page
@model BikeRental.Pages.LoginModel
@{
}
<div class="container mt-5">
    <div class ="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Login</h1>
                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                <form method="post">
                    <div class="mb-3">
                        <label class="form-label" asp-for="Model.Email">Email</label>
                        <input type="text" asp-for="Model.Email" class="form-control" />
                        <span asp-validation-for="Model.Email" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" asp-for="Model.Password">Password</label>
                        <input type="password" asp-for="Model.Password" class="form-control" />
                        <span asp-validation-for="Model.Password" class="text-danger"></span>
                    </div>
                    <dv class="mb-3">
                        <input type="checkbox" asp-for="Model.RememberMe" class="form-check-input" />
                        <label class="form-check-label" asp-for="Model.RememberMe">Remember Me?</label>
                    </dv>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Login</button>
                    </div>
                </form>
         </div>
     </div>    
</div>

BikeRental/Pages/Logout.cshtml
@page
@model BikeRental.Pages.LogoutModel
@{
}

<form method="post">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-12 col-lg-4">
                <p>Are you sure you want to logout?</p>
                <p>
                    <button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
                    <button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
                </p>
            </div>
        </div>
    </div>
</form>

BikeRental/Pages/Register.cshtml
@page
@model BikeRental.Pages.RegisterModel
@{
}

<div class="container mt-5">
    <div class ="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Register</h1>
                <form method="post">
                    <div asp-validation-summary="All" class="text-danger">
                    </div>
                    <div class="mb-3">
                        <label class="form-label" asp-for="Model.Email">Email</label>
                        <input type="text" asp-for="Model.Email" class="form-control" />
                        <span asp-validation-for="Model.Email" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" asp-for="Model.Password">Password</label>
                        <input type="password" asp-for="Model.Password" class="form-control" />
                        <span asp-validation-for="Model.Password" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label class="form-label" asp-for="Model.ConfirmPassword">ConfirmPassword</label>
                        <input type="password" asp-for="Model.ConfirmPassword" class="form-control" />
                        <span asp-validation-for="Model.ConfirmPassword" class="text-danger"></span>
                    </div>
                    <dv class="mb-3">
                        <button type="submit" class="btn btn-primary">Register</button>
                    </dv>
                </form>
        </div>    
    </div>

</div>

BikeRental/Pages/SuccessRegistration.cshtml
@page
@model BikeRental.Pages.SuccessRegistrationModel
@{
}
<div class="text-center">
    <h6 class="display-6">Registration Success.</h6>
</div>